### PR TITLE
Fix claim moduleaccount

### LINKED ISSUE #247: Add RPC endpoint to query claim module balance

### PR DESCRIPTION
**Pull request by sunnya97**
closes #247

### CODE REVIEW

File: cmd/osmosisd/cmd/genesis.go [hunk 1]
```diff
@@ -451,7 +452,8 @@ func TestnetGenesisParams() GenesisParams {
 	genParams.ClaimParams = claimtypes.Params{
 		AirdropStartTime:   genParams.GenesisTime,
 		DurationUntilDecay: time.Second * 10, // 60 days = ~2 months
-		DurationOfDecay:    time.Hour * 5,    // 120 days = ~4 months
+		DurationOfDecay:    time.Second * 30, // 120 days = ~4 months
```
Comment (ValarDragon) [inline cmd/osmosisd/cmd/genesis.go:455]: Incorrect comment.

Comment (ValarDragon) [reply cmd/osmosisd/cmd/genesis.go:455]: Why is this so low for the testnet?

Comment (ValarDragon) [reply cmd/osmosisd/cmd/genesis.go:455]: Imo it should be like 1 day
