### PR TITLE
Fix REST query total liquidity

### LINKED ISSUE #246: REST query for total_liquidity returns an error
Querying the gamm/total_liquidity through REST endpoint returns the following message:
```
{
  "code": 3,
  "message": "type mismatch, parameter: poolId, error: strconv.ParseUint: parsing \"total_liquidity\": invalid syntax",
  "details": []
}
```

However, querying the total_liquidity through the CLI returns a normal response:
```
liquidity:
- amount: "9998121"
  denom: ion
- amount: "500105"
  denom: uosmo
```

### PR DESCRIPTION
**Pull request by sunnya97**
closes #246

### CODE REVIEW

**Comment by ValarDragon** [comment]
Why are there swagger changes here?

File: cmd/osmosisd/cmd/init.go [hunk 1]
```diff
@@ -89,6 +89,7 @@ func InitCmd(mbm module.BasicManager, defaultNodeHome string) *cobra.Command {
 
 			appConfig := appcfg.DefaultConfig()
 			appConfig.API.Enable = true
+			appConfig.API.Swagger = true
```
Comment (ValarDragon) [inline cmd/osmosisd/cmd/init.go:92]:
```suggestion
			appConfig.API.Swagger = false
```

Comment (sunnya97) [inline cmd/osmosisd/cmd/init.go:92]:
```suggestion
```

**Review by ValarDragon — APPROVED** [review]
